---
- hosts: localhost
  connection: local
  roles:
    - { role: common, become: yes }
    - { role: nvm, become: no }
    - { role: uv, become: no }
    - { role: x-cmd, become: no }
    - { role: gemini, become: no }
    - { role: ansible-lint, become: no }
